---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skincarequiz-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: starbucskincarequiz
  template:
    metadata:
      labels:
        app: skincarequiz
    spec:
      containers:
      - name: skincarequiz-container
        image: tanveernz/skincarequiz:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skincarequiz-service
spec:
  type: LoadBalancer
  selector:
    app: skincarequiz
  ports:
  - port: 80
    targetPort: 3000
