apiVersion: apps/v1
kind: Deployment
metadata:
  name: skincarequiz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skincarequiz
  template:
    metadata:
      labels:
        app: skincarequiz
    spec:
      containers:
      - name: skincarequiz-container
        image: tanveernz/skincarequiz:fixed  
        ports:
        - containerPort: 5173  
        command: ["npm"]
        args: ["run", "dev", "--", "--host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: skincarequiz-service
spec:
  type: LoadBalancer
  selector:
    app: skincarequiz
  ports:
  - port: 80
    targetPort: 5173  